### ISSUE TITLE
When a merged attack gets parried, the "Add Thousands Separator" comma does not append to the text

### ISSUE THREAD

**Issue by CrowJJ** [TechHypno/ClassicFCT#13]
Sometimes the "Add Thousands Separator" comma won't append. The only clue I have is that one of the merged swings is a parry. Please see the attached video with the combat log for two instances:

https://user-images.githubusercontent.com/43883600/185675861-7857e5d2-ddc7-48ca-ac01-9072d953c772.mp4

**Comment by TechHypno** [comment]
very good clue, try this https://www.curseforge.com/wow/addons/classic-floating-combat-text/files/3942321

**Comment by CrowJJ** [comment]
That appears to have fixed it - thanks! Great addon as always.
