### ISSUE TITLE
CBTH on Friendly Nameplates

### ISSUE THREAD

**Issue by itsmekasta** [TechHypno/ClassicFCT#15]
I'm using the latest release and it seems that CBTH isn't working on friendly nameplates within instances. It only works with the centered screen feature only.

Is this intended or a bug?

It would be awesome, if the healing numbers work the same way as damage just on friendly nameplates as healer.

**Comment by TechHypno** [comment]
This isn't possible due to API restrictions put in by Blizzard. Specifically attaching anything like text to a nameplate is considered a modification of the nameplate and modifying friendly nameplates in instances isn't allowed.
