### ISSUE TITLE
Damage Received

### ISSUE THREAD

**Issue by silverselo** [TechHypno/ClassicFCT#17]
Hi

sorry to open an issue but I dont know how to contact you otherwise.
Is it possible to make the addon also work for Damage Taken (Dodge,Parry etc.) included.
Love the customisation of the addon.

**Comment by TechHypno** [comment]
It is possible but I wouldnt hold my breath if I were you. I personally use msbt for incoming damage. I'm curious if you have any reasons against using msbt together with cfct.

**Comment by silverselo** [comment]
The only reason I have is , that I would have to use two Addons. Still thanks for the anwser and awesome addon.
