### ISSUE TITLE
(small issue) text above wrong frame

### ISSUE THREAD

**Issue by Stefangansevles** [TechHypno/ClassicFCT#2]
Its not a breaking bug by any means, but i decided to report it anyway. 

If you damage an enemy, and switch to another enemy, the combat text will display above the selected creature, even if that is far away

see: 

![](https://i.imgur.com/j6HjkmO.png)

**Comment by TechHypno** [comment]
By default the addon is set to only display damage text on your target nameplate. This is to prevent text from overlapping.
With the Blizzard's API restrictions its impossible to have damage text displaying on multiple nameplates without overlap.
You can change it to display text on individual nameplates in the options, but then text from adjacent nameplates will overlap.
