### ISSUE TITLE
Classic FCT abbreviated numbers "k"

### ISSUE THREAD

**Issue by JulianJohansen** [TechHypno/ClassicFCT#22]
Hello. I'm trying to remove the abbreviation letter "k" for thousands in your addon but with no luck. eg instead of displaying 300000 as 300k, im trying to display it as 300 without the "k".

**Comment by TechHypno** [comment]
not currently possible, ill keep this open for later

**Comment by JulianJohansen** [comment]
Thanks but i actually managed to alter it to be able to this. I'll send you
the code if you want.
