### ISSUE TITLE
9.1 PTR change

### ISSUE THREAD

**Issue by anaander** [TechHypno/ClassicFCT#3]
Blizzard has removed these variables

```
SCHOOL_MASK_NONE	= 0x00;
SCHOOL_MASK_PHYSICAL	= 0x01;
SCHOOL_MASK_HOLY	= 0x02;
SCHOOL_MASK_FIRE	= 0x04;
SCHOOL_MASK_NATURE	= 0x08;
SCHOOL_MASK_FROST	= 0x10;
SCHOOL_MASK_SHADOW	= 0x20;
SCHOOL_MASK_ARCANE	= 0x40;
```

from the constants.lua on the 9.1 PTR. Just a head's up.

Note that adding these values to your config.lua resolves the issue.

**Comment by TechHypno** [comment]
thanks for the head's up, appreciate it.
