### ISSUE TITLE
Per-Spell Merge Interval

### ISSUE THREAD

**Issue by akbyrd** [TechHypno/ClassicFCT#4]
I absolutely love the addon. It does a great job of merging events, unlike other combat text addons I've tried.

I do have a request regarding merging though. I'd like to be able to set a per-spell interval. Fury Warriors have a couple of spells that perform multiple hits over a small duration. Namely, Whirlwind and Rampage. In order to merge all of these events properly and show a single hit I have to set my interval to 0.6 seconds, measured from the first event. Unfortunately, this is a rather log duration and has the effect of making the combat text for all my other abilities feel pretty slow.

I'd like to be able to keep the global interval to something like 0.1 seconds, then add an override specifically for Whirlwind and Rampage that raises the interval slightly to capture all the events. Parrot is another combat text addon that has this custom interval support.

If the context helps at all, here's the overall look I have set up.
![Scrolling Combat Text](https://user-images.githubusercontent.com/484784/136123620-085dcdab-b6fe-4222-9265-ff91a7b9c83c.gif)

**Comment by TechHypno** [comment]
> What are the merge categories?
need at least 2 categories for tracking by spell ids or spell icons.

**Comment by TechHypno** [comment]
working on this

**Comment by TechHypno** [comment]
Added this
