### ISSUE TITLE
multiple errrors

### ISSUE THREAD

**Issue by Weetbix813** [TechHypno/ClassicFCT#7]
Hi I received the following error over and over when logging in today:

867x ClassicFCT\main.lua:713: attempt to index field 'Config' (a nil value)
[string "@ClassicFCT\main.lua"]:713: in function <ClassicFCT\main.lua:712>
[string "@ClassicFCT\main.lua"]:863: in function <ClassicFCT\main.lua:853>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'Config' (a nil value)"
CFCT = <table> {
 enabled = true
 eventCache = <table> {
 }
 _testMode = false
 DamageRollingAverage = <function> defined @ClassicFCT\main.lua:30
 GetNamePlateUnitByGUID = <function> defined @ClassicFCT\main.lua:903
 UnitHealthMax = <function> defined @ClassicFCT\main.lua:913
 Test = <function> defined @ClassicFCT\main.lua:747
 frame = ClassicFCT.frame {
 }
 fontStringCache = <table> {
 }
 Animating = <table> {
 }
}
pairs = <function> defined =[C]:-1
eventCache = <table> {
}
now = 647887.539000
ipairs = <function> defined =[C]:-1
DispatchText = <function> defined @ClassicFCT\main.lua:601

**Comment by TechHypno** [comment]
Hey thanks for reporting but this error is caused in main.lua because config.lua failed to execute. I would need the error that precedes this one. It should be referencing config.lua.
