### ISSUE TITLE
lua error since new version

### ISSUE THREAD

**Issue by nicovermeiren** [TechHypno/ClassicFCT#8]
Hello i'm having lua errors since new version and cant seem to get it to work

Date: 2021-11-06 19:34:50
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ClassicFCT\config.lua line 1017:
   table index is nil
Debug:
   [string "@ClassicFCT\config.lua"]:1017: in main chunk
Locals:
addonName = "ClassicFCT"
CFCT = <table> {
}
tinsert = <function> defined =[C]:-1
tremove = <function> defined =[C]:-1
format = <function> defined =[C]:-1
strlen = <function> defined =[C]:-1
strsub = <function> defined =[C]:-1
gsub = <function> defined =[C]:-1
floor = <function> defined =[C]:-1
sin = <function> defined compat.lua:36
cos = <function> defined compat.lua:21
asin = <function> defined compat.lua:17
acos = <function> defined compat.lua:16
random = <function> defined =[C]:-1
select = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1
ipairs = <function> defined =[C]:-1
bitband = <function> defined =[C]:-1
GetSpellInfo = <function> defined =[C]:-1
IsRetail = false
IsClassic = false
IsBCC = true
DefaultPresets = <table> {
 Classic = <table> {
 }
 Mists of Pandaria = <table> {
 }
}
DefaultConfig = <table> {
 petheal = <table> {
 }
 filterRelativeEnabled = false
 attachModeFallback = true
 filterAverageThreshold = 10
 mergeEventsBySchool = true
 petspellmiss = <table> {
 }
 preventOverlap = true
 mergeEvents = false
 mergeEventsIntervalMode = "last"
 inheritNameplates = false
 abbreviateNumbers = false
 filterAbsoluteThreshold = 100
 autocrit = <table> {
 }
 preventOverlapSpacingX = 30
 pethealcrit = <table> {
 }
 petautocrit = <table> {
 }
 heal = <table> {
 }
 pethealmiss = <table> {
 }
 areaX = 0
 healcrit = <table> {
 }
 mergeEventsInterval = 0.100000
 petauto = <table> {
 }
 healmiss = <table> {
 }
 petautomiss = <table> {
 }
 petspellcrit = <table> {
 }
 mergeEventsBySpellID = false
 kiloSeparator = false
 animDuration = 1.500000
 petspell = <table> {
 }
 spellIconOffsetY = 0
 textStrata = "MEDIUM"
 sortMissPrio = false
 dontOverlapNameplates = false
 areaNY = 0
 spellmiss = <table> {
 }
 mergeEventsByGuid = false
 animSpeed = 1
 filterAbsoluteEnabled = false
 preventOverlapSpacingY = 50
 spell = <table> {
 }
 attachMode = "tn"
 areaY = 150
 automiss = <table> {
 }
 auto = <table> {
 }
 mergeEventsBySpellIcon = true
 colorTable = <table> {
 }
 filterRelativeThreshold = 10
 mergeEventsCounter = true
 spellcrit = <table> {
 }
 spellIconOffsetX = 0
 areaNX = 0
 spellIconAspectRatio = 1
 filterAverageEnabled = false
 spellIconZoom = 1
 sortByDamage = false
}
DefaultVars = <table> {
 enabled = true
 hideBlizzHeals = true
 forceCVars = true
 hideBlizz = true
 lastVersion = ""
 selectedPreset = ""
 characterSpecificConfig = false
}
DefaultCharVars = <table> {
 enabled = true
 hideBlizzHeals = true
 forceCVars = true
 hideBlizz = true
 selectedPreset = ""
}
DefaultTables = <table> {
 filterSpellBlacklist = <table> {
 }
 mergeEventsIntervalOverrides = <table> {
 }
}
ClassSpecificTables = <table> {
 filterSpellBlacklist = true
 mergeEventsIntervalOverrides = true
}
(for index) = 6
(for limit) = 11
(for step) = 1
i = 6
class = nil
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 filterSpellBlacklist = true
 mergeEventsIntervalOverrides = true
}
(for control) = "filterSpellBlacklist"
k = "filterSpellBlacklist"
v = true
(*temporary) = <table> {
 HUNTER = <table> {
 }
 WARRIOR = <table> {
 }
 PALADIN = <table> {
 }
 ROGUE = <table> {
 }
 PRIEST = <table> {
 }
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*tempora
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AngryAssignments, vv1.14.2tbc
  Atlas, vv1.49.01
  AtlasClassicWoW, vv1.49.00
  AtlasLootClassic, vv2.3.4-bcc
  AtlasLootClassicData, vv2.3.4-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.3.4-bcc
  Attune, v245
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Bagnon, v9.1.3
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicFCT, vB0.86b
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v2.5.2.20502 <none>
  (ck=31e)

**Comment by phoeshow** [comment]
#10 
maybe this will resolve the problem.
